name: update
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**.yml
  schedule:
    - cron: 0 * * * *

jobs:
  update_main:
    uses: ./.github/workflows/update_branch.yml
    with:
      ref: main

  update_stable:
    uses: ./.github/workflows/update_branch.yml
    with:
      ref: stable
