name: update
on:
  push:
    branches:
    paths:
      - .github/workflows/**.yml
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  update_main:
    uses: ./.github/workflows/update_branch.yml
    with:
      reparse: ${{ github.event_name == 'workflow_dispatch' }} 
      ref: main

  update_stable:
    uses: ./.github/workflows/update_branch.yml
    with:
      reparse: ${{ github.event_name == 'workflow_dispatch' }} 
      ref: stable
