name: update_data
on:
  push:
    branches:
    paths:
      - .github/workflows/update.yml
      - .github/workflows/build.yml
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      use_release: ${{ github.ref_name == 'stable' }}

  update:
    name: update
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run (schedule)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: ./PoliNetwork.Graduatorie.Parser/bin/Release/net7.0/PoliNetwork.Graduatorie.Parser

        ### REPARSE (push, manual trigger)
      - name: Run (reparse)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: ./PoliNetwork.Graduatorie.Parser/bin/Release/net7.0/PoliNetwork.Graduatorie.Parser --reparse

      - name: Push generated files
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          cwd: "./local/"
          add: "data"
          message: ${{ github.event_name != 'workflow_dispatch' && '[auto] update data with reparse' || '[auto] update data' }}
          author_name: PoliNetwork
          author_email: PoliNetwork@users.noreply.github.com
          pathspec_error_handling: exitImmediately
