name: update_data
on:
  push:
    branches:
    paths:
      - .github/workflows/update.yml
      - .github/workflows/build.yml
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    env:
      IS_REPARSE: ${{ github.event_name == 'workflow_dispatch' }}
      IS_RELEASE_BRANCH: ${{ github.ref_name == 'stable' }}

    steps:
      - name: Build script
        uses: ./.github/workflows/build.yml
        with:
          use_release: $IS_RELEASE_BRANCH

      - name: Run (schedule)
        if: ${{ !env.IS_REPARSE }}
        run: dotnet run --project ./PoliNetwork.Graduatorie.Parser/PoliNetwork.Graduatorie.Parser.csproj

        ### REPARSE (push, manual trigger)
      - name: Run (reparse)
        if: ${{ env.IS_REPARSE }}
        run: dotnet run --project ./PoliNetwork.Graduatorie.Parser/PoliNetwork.Graduatorie.Parser.csproj --reparse

      - name: Push generated files
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          cwd: "./local/"
          add: "data"
          message: ${{ env.IS_REPARSE == 'true' && '[auto] update data with reparse' || '[auto] update data' }}
          author_name: PoliNetwork
          author_email: PoliNetwork@users.noreply.github.com
          pathspec_error_handling: exitImmediately
