name: update_branch
on:
  workflow_call:
    inputs:
      reparse:
        required: false
        default: false
        type: boolean

      ref:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      use_release: ${{ inputs.ref == 'stable' }}
      artifact_name: dist_${{ inputs.ref }}

  run_update_branch:
    name: run and update branch
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build dist
        uses: actions/download-artifact@v3
        with:
          name: dist_${{ inputs.ref }}
          path: dist

      - uses: actions/checkout@v3
        with:
          path: ./local/
          ref: ${{ inputs.ref }}

      - name: make script executable
        run: chmod +x ./dist/PoliNetwork.Graduatorie.Parser

      - name: Run (schedule)
        if: ${{ inputs.reparse == 'false' }}
        run: ./dist/PoliNetwork.Graduatorie.Parser

        ### REPARSE (push, manual trigger)
      - name: Run (reparse)
        if: ${{ inputs.reparse == 'true' }}
        run: ./dist/PoliNetwork.Graduatorie.Parser --reparse

      - name: Push generated files
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          cwd: "./local/"
          add: "data"
          message: ${{ inputs.reparse == 'true' && '[auto] update data with reparse' || '[auto] update data' }}
          author_name: PoliNetwork
          author_email: PoliNetwork@users.noreply.github.com
          pathspec_error_handling: exitImmediately
